title: "Jordan Thuo's Engineering Portfolio"
description: "A showcase of my engineering projects, reports, and documents."
theme: jekyll-theme-cayman  # Replace with any theme you prefer from GitHub Pages
